version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/PythonClient"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      include: scope
      prefix: ci