ARG BASE_IMAGE=ghcr.io/epicgames/unreal-engine:dev-slim-5.5.4
FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	apt-get install -y --no-install-recommends \
		python3=3.11.2-1+b1 \
		python3-pip=23.0.1+dfsg-1 \
		gosu=1.14-2+b1 && \
	rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir pip==24.0 && \
	pip3 install --no-cache-dir cosysairsim==3.3.1

RUN adduser --force-badname --disabled-password --gecos '' --shell /bin/bash airsim_user && \
	echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
	adduser airsim_user sudo && \
	adduser airsim_user audio && \
	adduser airsim_user video

USER airsim_user
WORKDIR /home/airsim_user

RUN mkdir -p /home/airsim_user/Documents/AirSim
COPY settings.json /home/airsim_user/Documents/AirSim
#ADD Documents /home/airsim_user/Documents

RUN gosu root chown -R airsim_user /home/airsim_user
