ARG BASE_IMAGE=ghcr.io/epicgames/unreal-engine:dev-slim-5.5.4
FROM $BASE_IMAGE AS builder

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	apt-get install -y --no-install-recommends \
		python3=3.11.2-1+b1 \
		python3-pip=23.0.1+dfsg-1 \
		rsync=3.2.7-1 \
		wget=1.21.3-1+b1 \
		cmake=3.25.1-1 && \
	rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install --no-cache-dir pip==24.0 && \
	pip3 install --no-cache-dir cosysairsim==3.3.1

FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
	apt-get install -y --no-install-recommends \
		python3=3.11.2-1+b1 \
		python3-pip=23.0.1+dfsg-1 && \
	rm -rf /var/lib/apt/lists/*

USER ue4
COPY --chown=ue4:ue4 --from=builder /home/ue4 /home/ue4

WORKDIR /home/ue4
