ARG BASE_IMAGE=ghcr.io/epicgames/unreal-engine:dev-5.4.3
FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
	rsync \
    sudo \
    wget \
    x11-xserver-utils

RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    adduser ue5 sudo

USER ue5
RUN cd /home/ue5 && \
	git clone --progress https://github.com/Cosys-Lab/Cosys-AirSim.git && \
	cd AirSim && \
	./setup.sh && \
	./build.sh

WORKDIR /home/ue5
