ARG BASE_IMAGE=ghcr.io/epicgames/unreal-engine:dev-slim-5.6.1
FROM $BASE_IMAGE

USER root
RUN DEBIAN_FRONTEND=noninteractive apt-get update

RUN apt-get install -y --no-install-recommends \
	python3 \
	python3-pip \
	rsync \
	wget \
	sudo

RUN apt-get install -y --upgrade cmake

RUN python3 -m pip install --upgrade pip && \
pip3 install cosysairsim

USER ue4
RUN cd /home/ue4 && \
	git clone --progress https://github.com/Cosys-Lab/Cosys-AirSim.git && \
	cd Cosys-AirSim && \
	./setup.sh && \
	./build.sh

WORKDIR /home/ue4
