float32 rssi # Received signal strength intensity
float32 rssi_spread # spread on the RSSI measurements

float32 num_bursts #number of bursts in one measurement
float32 burst_duration #duration of one burst
float32 ftms_per_burst #number of Fine Time Measurements per burst

float32 rtt_avg #average round trip time for all measurements
float32 rtt_spread # spread of the round trip time measurements
float32 rtt_variance # variance of the round trip time for all measurements
