FROM ros:foxy-ros-base

RUN apt-get update && \
	apt-get install -y --no-install-recommends \
		apt-utils=0.7.42.16 \
		gcc-8=8.4.0-3ubuntu2 \
		g++-8=8.4.0-3ubuntu2 \
		"ros-$ROS_DISTRO-tf2-sensor-msgs" \
		"ros-$ROS_DISTRO-tf2-geometry-msgs" \
		"ros-$ROS_DISTRO-mavros" \
		"ros-$ROS_DISTRO-vision-opencv" \
		"ros-$ROS_DISTRO-image-transport" \
		libyaml-cpp-dev=0.6.2-4ubuntu1 && \
	echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc && \
	rm -rf /var/lib/apt/lists/* && \
	apt-get clean