uint32 fp1_amplitude
uint32 fp2_amplitude
uint32 fp3_amplitude
uint32 cir_power # Channel Impule Response power
uint32 preamble_count # Size of the preamble message
float32 fppl # First peak power level
float32 rssi # Received signal strength intensity
float32 index_fp # Index of the first peak in the CIR
float32[] cir_magnitude # Channel Impulse Response magnitude signal
float32[] cir_phase # Channel Impulse Response phase signal
int16[] cir_imag # Channel Impulse Response imaginary signal
int16[] cir_real # Channel Impulse Response real signal

