name: Build

on:
  - pull_request

jobs:
  build_linux:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      run: ./setup.sh --no-full-poly-car

    - name: Build
      run: ./build.sh

    - name: Verify MavLink built
      run: ./build_release/output/bin/MavLinkTest --help
